library:
  source-dirs: src
tests:
  HaskellVM-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - HaskellVM
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- directory
- base >= 4.7 && < 5
name: HaskellVM
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/HaskellVM
license: BSD3
executables:
  HaskellVM-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellVM
description: Please see the README on GitHub at <https://github.com/githubuser/HaskellVM#readme>
